config/routes.rb
Dancevent::Application.routes.draw do
  resources :events

  devise_for :users

  root 'index#index'


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
    
    can :read, Event 
    can :create, Event
    can :update, Event, :user_id => user.id
    can :destroy, Event, :user_id => user.id
    

    
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
	extend FriendlyId
	friendly_id :name, use: :slugged

	belongs_to :user
	validates_presence_of :name, :description, :start_time, :end_time

	has_attached_file :logo, :styles => {:banner => "800x295" ,:medium => "300x300>", :thumb => "100x100#" }, :default_url => ':style/missing.png'
  validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  layout "united"

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

   before_filter do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource :find_by => :slug

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user = current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :start_time, :end_time, :location, :logo)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

	def index
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/events/_form.html.erb
 <div class='well'>
  <%= bootstrap_form_for(@event, style: :horizontal, left: "col-sm-2", right: "col-sm-6", :html => { :multipart => true }) do |f| %>
    
    <%= f.text_field :name%>

    <%= f.text_area :description %>


    <div class="form-group <% if @event.errors.any? and !@event.errors[:start_time].blank? %> has-error <%end%>">
        <label class="col-sm-2 control-label" for="event_description">Start Time</label>
        <div class='date col-sm-6  datetimepicker-group input-group' >
          <%= f.datetime_field :start_time, :class=> 'form-control',  value: @event.start_time.respond_to?('strftime') ? @event.start_time.strftime('%Y-%m-%d %H:%M') : nil  %>
            <span class="input-group-addon">
              <span data-icon-element="" class="fa fa-calendar"></span>
            </span>
        </div>
        <% if @event.errors.any? and !@event.errors[:start_time].blank? %>
          <div class="col-sm-2"></div>
          <div class='col-sm-6'>
            <span class="help-block"><%= @event.errors[:start_time].first %></span>
          </div>
        <% end %>
    </div>

     <div class="form-group <% if @event.errors.any? and !@event.errors[:end_time].blank? %> has-error <%end%>">
        <label class="col-sm-2 control-label" for="event_description">End Time</label>
        <div class='date col-sm-6 datetimepicker-group input-group'>
          <%= f.datetime_field :end_time, :class=> 'form-control',  value: @event.end_time.respond_to?('strftime') ? @event.end_time.strftime('%Y-%m-%d %H:%M') : nil  %>
            <span class="input-group-addon">
              <span data-icon-element="" class="fa fa-calendar"></span>
            </span>
        </div>
        <% if @event.errors.any? and !@event.errors[:end_time].blank? %>
          <div class="col-sm-2"></div>
          <div class='col-sm-6'>
            <span class="help-block"><%= @event.errors[:end_time].first %></span>
          </div>
        <% end %>
    </div>
    
    <%= f.text_field :location %>
    <%= f.file_field :logo %>
    
    <%= f.form_group do %>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")), events_path, :class => 'btn btn-default' %>
    <% end %>
  <% end %>

</div>


  <script type="text/javascript">
      $(function () {
          $('.datetimepicker-group').datetimepicker({ 
            format: 'YYYY-MM-DD HH:mm',
            icons: {
              time: "fa fa-clock-o",
              date: "fa fa-calendar",
              up: "fa fa-arrow-up",
              down: "fa fa-arrow-down"
            }
          }
        );
      });
  </script>
 

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<%= link_to t('.new', :default => t("New event")), new_event_path, :class => 'btn btn-primary' %>


<div class="page-header">
  <h1>Events</h1>
</div>

  <div class="list-group">
   <% @events.each do |event| %>
      <a href="<%= event_path(event) %>" class="list-group-item">
        <div class="row">
          <div class="col-sm-2">
             <%= image_tag event.logo.url(:thumb), :class => 'img-thumbnail' %>
          </div>

          <div class="col-sm-8">
            <h4 class="list-group-item-heading"><%= event.name %></h4>
            <p class="list-group-item-text"><%= simple_format(truncate(event.description, :length => 130)) %></p>
            <span class="badge"> <%= event.start_time.respond_to?('strftime') ? event.start_time.strftime('%Y-%m-%d %H:%M') : '' %></span>
          </div>
        </div>
        
      </a>
    <% end %> 
  </div>

 

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<%- model_class = Event -%>

<div class="">
  <%= image_tag @event.logo.url(:banner), :class => 'img-thumbnail' %>

  <div class="panel panel-default">
    <div class="panel-body">
        <h2><%= @event.name %></h2>

        <h4>
          <span class="label label-info">
            <i class="fa fa-clock-o"></i>
          </span>
          <span class="label label-info">
            <%= @event.start_time.respond_to?('strftime') ? @event.start_time.strftime('%Y-%m-%d %H:%M'): '' %> - 
            <%= @event.end_time.respond_to?('strftime') ? @event.end_time.strftime('%Y-%m-%d %H:%M') : '' %>
          </span>
        </h4>
        

        <h4>
          <span class="label label-default">
            <i class="fa fa-location-arrow"></i>
          </span>
          <span class="label label-default">
            <%= @event.location %>
          </span>
        </h4>

        <p><%= simple_format(@event.description) %></p> 

       </div>
    </div>

    <% if can?(:update, @event) and can?(:destroy, @event) %>
      <div class="panel panel-default">
        <div class="panel-body">

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_event_path(@event), :class => 'btn btn-default' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        event_path(@event),
                        :method => 'delete',
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-danger' %>
      </div>
    </div>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dance Event" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>


    <!-- Optional theme -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">dance.event</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="<%= events_path %>">Home</a></li>
            <li><a href="<%= new_user_session_path%>">Sign in</a></li>
            <li><a href="<%= new_user_registration_path%>">Sign up</a></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
           
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
      <div class="row" style="margin-top:80px;">
        <div class="col-lg-9">
            <%= bootstrap_flash %>
             <%= yield %>
        </div>
      </div><!--/row-->

     

      <footer>
        <p>&copy; Dance Event 2014</p>
      </footer>
    </div> <!-- /container -->


  </body>
</html>

app/views/layouts/united.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "dancevent" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

    <%= javascript_include_tag "application" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>

  </head>
  <body>


    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= events_path %>">dance.event</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="<%= events_path %>">Home</a></li>
            <li><a href="<%= new_user_session_path%>">Sign in</a></li>
            <li><a href="<%= new_user_registration_path%>">Sign up</a></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
           
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
      <div class="row" style="margin-top:80px;">
        <div class="col-xs-12 col-md-8">
            <%= bootstrap_flash %>
            <%= yield %>
        </div>
      </div><!--/row-->

     

      <footer>
        <p>&copy; Dance Event 2014</p>
      </footer>
    </div> <!-- /container -->



  </body>
</html>